name: Bug Report
description: A report about an issue, crash or similar.
title: "[Issue]: "
assignees:
  - Gbergz
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A short explanation of what happened.
      value: ""
    validations:
      required: true
  - type: textarea
    id: versionpack
    attributes:
      label: Pack Version
      description: Put the pack version you are on here.
      render: shell
  - type: checkboxes
    id: addedmods
    attributes:
      label: Are you using OptiFine, Rubidium, or Oculus?
      options:
        - label: Using OptiFine
        - label: Using Rubidium
        - label: Using Rubidium + Oculus
        - label: No. None of them. Unmodified.
          required: true
  - type: checkboxes
    id: server
    attributes:
      label: Are you on a Server?
      options:
        - label: Yes.
        - label: No.
          required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output / crash report.
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: anything
    attributes:
      label: Anything else that we should know?
      description: Optional.
      render: shell
